### ISSUE TITLE
What is the license?

### ISSUE THREAD

**Issue by brettchalupa** [AgilionApps/VagrantDevEnv#14]
Howdy all. :smile:

I realized I forked this project without knowing what the license is. Having no license implies that it is all rights reserved, which is fine. I just want to make sure before I modify or adjust the fork.

**Comment by alanpeabody** [comment]
Thanks Brett, I will upload one, probably MIT or Apache 2. Need to double check what we are using first.

**Comment by brettchalupa** [comment]
Thank you, I appreciate it!
